In [3]:
!pip install -q transformers datasets evaluate rouge_score sentencepiece accelerate

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.4 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [4]:
import torch
import numpy as np

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

import evaluate

In [5]:
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

In [6]:
dataset = load_dataset("ccdv/pubmed-summarization")

print(dataset)

README.md:   0%|          | 0.00/3.80k [00:00<?, ?B/s]

section/train-00000-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  210MB

section/train-00000-of-00005.parquet: downloading bytes:           |  0.00B

section/train-00001-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  208MB

section/train-00001-of-00005.parquet: downloading bytes:           |  0.00B

section/train-00002-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  207MB

section/train-00002-of-00005.parquet: downloading bytes:           |  0.00B

section/train-00003-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  211MB

section/train-00003-of-00005.parquet: downloading bytes:           |  0.00B

section/train-00004-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  210MB

section/train-00004-of-00005.parquet: downloading bytes:           |  0.00B

section/validation-00000-of-00001.parque(…): reconstructing file:   0%|          |  0.00B / 59.0MB

section/validation-00000-of-00001.parque(…): downloading bytes:           |  0.00B

section/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 58.9MB

section/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/119924 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6633 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6658 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['article', 'abstract'],
        num_rows: 119924
    })
    validation: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6633
    })
    test: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6658
    })
})

In [7]:
print("ARTICLE:")
print(dataset["train"][0]["article"][:2000])

print("\nABSTRACT:")
print(dataset["train"][0]["abstract"])

ARTICLE:
a recent systematic analysis showed that in 2011 , 314 ( 296 - 331 ) million children younger than 5 years were mildly , moderately or severely stunted and 258 ( 240 - 274 ) million were mildly , moderately or severely underweight in the developing countries .
 in iran a study among 752 high school girls in sistan and baluchestan showed prevalence of 16.2% , 8.6% and 1.5% , for underweight , overweight and obesity , respectively .
 the prevalence of malnutrition among elementary school aged children in tehran varied from 6% to 16% .
 anthropometric study of elementary school students in shiraz revealed that 16% of them suffer from malnutrition and low body weight .
 snack should have 300 - 400 kcal energy and could provide 5 - 10 g of protein / day . nowadays , school nutrition programs are running as the national programs , world - wide . national school lunch program in the united states
 there are also some reports regarding school feeding programs in developing countries . in vietnam ,
 school base program showed an improvement in nutrient intakes . in iran a national free food program ( nffp )
 is implemented in elementary schools of deprived areas to cover all poor students . however , this program is not conducted in slums and poor areas of the big cities so many malnourished children with low socio - economic situation are not covered by nffp . although the rate of poverty in areas known as deprived is higher than other areas , many students in deprived areas are not actually poor and can afford food .
 hence , nutritional value of the nffp is lower than the scientific recommended snacks for this age group .
 furthermore , lack of variety of food packages has decreased the tendency of children toward nffp . on the other hand ,
 the most important one is ministry of education ( moe ) of iran , which is responsible for selecting and providing the packages for targeted schools .
 the ministry of health ( moh ) is supervising the health situation of s

ABSTRACT:
background : the present study was carried out to assess the effects of community nutrition intervention based on advocacy approach on malnutrition status among school - aged children in shiraz , iran.materials and methods : this case - control nutritional intervention has been done between 2008 and 2009 on 2897 primary and secondary school boys and girls ( 7 - 13 years old ) based on advocacy approach in shiraz , iran .
 the project provided nutritious snacks in public schools over a 2-year period along with advocacy oriented actions in order to implement and promote nutritional intervention . for evaluation of effectiveness of the intervention growth monitoring indices of pre- and post - intervention were statistically compared.results:the frequency of subjects with body mass index lower than 5% decreased significantly after intervention among girls ( p = 0.02 ) .
 however , there were no significant changes among boys or total population .
 the mean of all anthropometric indices changed significantly after intervention both among girls and boys as well as in total population .
 the pre- and post - test education assessment in both groups showed that the student 's average knowledge score has been significantly increased from 12.5  3.2 to 16.8  4.3 ( p < 0.0001).conclusion : this study demonstrates the potential success and scalability of school feeding programs in iran .
 community nutrition intervention based on the advocacy process model is effective on reducing the prevalence of underweight specifically among female school aged children .

In [8]:
train_dataset = dataset["train"].select(range(5000))
validation_dataset = dataset["validation"].select(range(500))
test_dataset = dataset["test"].select(range(500))

print(len(train_dataset))
print(len(validation_dataset))
print(len(test_dataset))

5000
500
500

In [9]:
model_name = "t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  242MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [10]:
prefix = "summarize: "

def preprocess_function(examples):

    inputs = [
        prefix + text
        for text in examples["article"]
    ]

    model_inputs = tokenizer(
        inputs,
        max_length=512,
        truncation=True
    )

    labels = tokenizer(
        text_target=examples["abstract"],
        max_length=128,
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

In [11]:
tokenized_train = train_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=train_dataset.column_names
)

tokenized_validation = validation_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=validation_dataset.column_names
)

tokenized_test = test_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=test_dataset.column_names
)

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [12]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [13]:
rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [18]:
def compute_metrics(eval_pred):

    predictions, labels = eval_pred

    # Some Trainer versions return a tuple
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Convert predictions to numpy
    predictions = np.asarray(predictions)

    # Make sure token IDs are valid integers
    predictions = predictions.astype(np.int64)

    # Replace invalid label padding values (-100)
    labels = np.where(
        labels != -100,
        labels,
        tokenizer.pad_token_id
    )

    labels = np.asarray(labels).astype(np.int64)

    # Decode predictions
    decoded_predictions = tokenizer.batch_decode(
        predictions,
        skip_special_tokens=True
    )

    # Decode reference summaries
    decoded_labels = tokenizer.batch_decode(
        labels,
        skip_special_tokens=True
    )

    # Remove extra whitespace
    decoded_predictions = [
        pred.strip()
        for pred in decoded_predictions
    ]

    decoded_labels = [
        label.strip()
        for label in decoded_labels
    ]

    result = rouge.compute(
        predictions=decoded_predictions,
        references=decoded_labels
    )

    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"]
    }

In [25]:
training_args = Seq2SeqTrainingArguments(
    output_dir="./medical_summarizer",

    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,

    weight_decay=0.01,

    num_train_epochs=1,

    # IMPORTANT
    predict_with_generate=False,

    fp16=torch.cuda.is_available(),

    logging_steps=100,

    save_total_limit=2,

    report_to="none"
)

In [26]:
generation_max_length=128
generation_num_beams=4

In [27]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_train,
    eval_dataset=tokenized_validation,

    processing_class=tokenizer,

    data_collator=data_collator,

    compute_metrics=None
)

In [28]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1250, training_loss=2.7836473388671874, metrics={'train_runtime': 174.7935, 'train_samples_per_second': 28.605, 'train_steps_per_second': 7.151, 'total_flos': 676709007360000.0, 'train_loss': 2.7836473388671874, 'epoch': 1.0})

In [29]:
results = trainer.evaluate()

print(results)

{'eval_loss': 2.529456615447998}

In [30]:
def summarize_medical_report(text):

    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )

    inputs = {
        key: value.to(model.device)
        for key, value in inputs.items()
    }

    summary_ids = model.generate(
        **inputs,
        max_new_tokens=100,
        min_new_tokens=20,
        num_beams=4,
        early_stopping=True
    )

    summary = tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

    return summary

In [31]:
sample_report = """
A 56-year-old patient presented with persistent cough,
fever and shortness of breath for seven days.
Chest imaging demonstrated bilateral pulmonary infiltrates.
Laboratory investigations showed elevated inflammatory markers.
The patient was diagnosed with a respiratory infection
and was started on appropriate antimicrobial treatment.
"""

summary = summarize_medical_report(sample_report)

print("MEDICAL REPORT:")
print(sample_report)

print("\nAI GENERATED SUMMARY:")
print(summary)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

MEDICAL REPORT:

A 56-year-old patient presented with persistent cough,
fever and shortness of breath for seven days.
Chest imaging demonstrated bilateral pulmonary infiltrates.
Laboratory investigations showed elevated inflammatory markers.
The patient was diagnosed with a respiratory infection
and was started on appropriate antimicrobial treatment.


AI GENERATED SUMMARY:
a 56-year-old patient presented with persistent cough, fever and shortness of breath for seven days. the patient was diagnosed with a respiratory infection and was started on appropriate antimicrobial treatment.

In [32]:
import evaluate

rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [34]:
predictions = []
references = []

# Evaluate only 50 reports first
num_samples = 50

for i in range(num_samples):

    report = test_dataset[i]["article"]
    reference = test_dataset[i]["abstract"]

    generated = summarize_medical_report(report)

    predictions.append(generated)
    references.append(reference)

    if i < 3:
        print("=" * 80)
        print("GENERATED:")
        print(generated)

        print("\nREFERENCE:")
        print(reference)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
GENERATED:
anxiety affects quality of life in those living with parkinson's disease ( pd ) more so than overall cognitive status, motor deficits, apathy, and depression. however, our current understanding of anxiety and its impact on cognition in pd remains meager and lags far behind that of depression. however, few studies have specifically investigated the relationship between anxiety and cognition in pd. however

REFERENCE:
research on the implications of anxiety in parkinson 's disease ( pd ) has been neglected despite its prevalence in nearly 50% of patients and its negative impact on quality of life .
 previous reports have noted that neuropsychiatric symptoms impair cognitive performance in pd patients ; however , to date , no study has directly compared pd patients with and without anxiety to examine the impact of anxiety on cognitive impairments in pd .
 this study compared cognitive performance across 50 pd participants with and without anxiety ( 17 pda+ ; 33 pda ) , who underwent neurological and neuropsychological assessment .
 group performance was compared across the following cognitive domains : simple attention / visuomotor processing speed , executive function ( e.g. , set - shifting ) , working memory , language , and memory / new verbal learning .
 results showed that pda+ performed significantly worse on the digit span forward and backward test and part b of the trail making task ( tmt - b ) compared to the pda group .
 there were no group differences in verbal fluency , logical memory , or tmt - a performance . in conclusion ,
 anxiety in pd has a measurable impact on working memory and attentional set - shifting .

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
GENERATED:
small non - coding rnas are transcribed into mrna but remain untranslated in eukaryotic cells. they include sirna ( small interfering rna ), mirna ( microrna ), pirna ( piwi - interacting rna ) and snorna ( small nucleolar rna

REFERENCE:
small non - coding rnas include sirna , mirna , pirna and snorna .
 the involvement of mirnas in the regulation of mammary gland tumorigenesis has been widely studied while the role for other small non - coding rnas remains unclear . here
 we summarize the involvement of mirna in breast cancer onset and progression through regulating the cell cycle and cellular proliferation .
 the regulation of breast cancer stem cells and tumor regeneration by mirna is reviewed .
 in addition , the emerging evidence demonstrating the involvement of pirna and snorna in breast cancer is briefly described .

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
GENERATED:
ohss is a serious complication of ovulation induction, occurring in 1 - 10% of in vitro fertilization patients. this iatrogenic condition has a spectrum of clinical and laboratory manifestations ranging from mild to severe, even life - threatening conditions. among the serious manifestations of ohss are ascites and pleural effusion ( rizk and smitz

REFERENCE:
objective : to evaluate the efficacy and safety of outpatient management of severe ovarian hyperstimulation syndrome  ( ohss ) requiring placement of a pigtail catheter.methods : retrospective analysis of thirty - three consecutive patients who underwent in - vitro fertilization  ( 2003 - 2009 ) and developed severe / critical ohss requiring placement of a pigtail catheter .
 patients who were managed on outpatient basis were monitored by frequent office visits , daily phone calls , and received iv normal saline for hydration when required.results : in 3 patients  ( 9.1% ) ohss started early , requiring placement of a pigtail catheter 4.3 + 0.6 days after retrieval . in 30 patients  ( 90.9% )
 ohss started late  ( 14  4 days after retrieval ) .
 the mean amount of ascitic fluid drained immediately after placement of the catheter was 2085  1018 cc .
 the pigtail catheter was removed after 7.8  5.3 days .
 of the 31 patients who had embryo transfer  ( two had total freeze ) , 84% conceived .
 twenty - nine patients  ( 88% ) were managed on outpatient basis without any complications .
 four patients required hospital admission for 1 - 7 days  ( 3.0  2.7 ) .
 one patient with severe ohss was admitted for work up for chest pain .
 three patients with critical ohss with severe pleural effusion requiring thoracentesis were admitted for supportive measures.conclusion : the placement of a pigtail catheter resulted in safe and effective outpatient management for the majority of patients with severe ohss .

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [35]:
results = rouge.compute(
    predictions=predictions,
    references=references
)

print(results)

{'rouge1': np.float64(0.24247039983142038), 'rouge2': np.float64(0.09206051385343039), 'rougeL': np.float64(0.17052384015507827), 'rougeLsum': np.float64(0.2115147767019254)}

In [36]:
!pip install -q pypdf pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 9.3 MB/s eta 0:00:00

In [37]:
import pandas as pd
from pypdf import PdfReader
from google.colab import files

In [38]:
def extract_pdf_text(pdf_path):

    reader = PdfReader(pdf_path)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text

In [39]:
def extract_pdf_text(pdf_path):

    reader = PdfReader(pdf_path)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text

In [40]:
uploaded = files.upload()

filename = list(uploaded.keys())[0]

print("Uploaded file:", filename)

Saving Sample-filled-in-MR.pdf to Sample-filled-in-MR.pdf
Uploaded file: Sample-filled-in-MR.pdf

In [41]:
if filename.lower().endswith(".csv"):

    df = pd.read_csv(filename)

    print("CSV loaded successfully!")
    print("Columns:", df.columns.tolist())

    display(df.head())

elif filename.lower().endswith(".pdf"):

    medical_report = extract_pdf_text(filename)

    print("PDF loaded successfully!")
    print("\nExtracted text:")
    print(medical_report[:3000])

else:

    print("Please upload a CSV or PDF file.")

PDF loaded successfully!

Extracted text:
- 1 -

SAMPLE
(All names and details provided in this sample are fictitious.
Some fields have been deliberately left blank.)


MEDICAL REPORT

SECTION 1: PATIENT’S PARTICULARS

Full name of patient: Mr Tan Ah Kow

NRIC/FIN/Passport no. of patient: S1111111X

Age of patient: 55 years old

SECTION 2: DOCTOR’S PARTICULARS

Full name of doctor: Tan Ah Moi

NRIC/FIN/Passport no. of doctor: S2222222Z


MCR no. of doctor: 333333

Hospital / Clinic name and address: 1 Blackacre Hospital, Singapore 01010101



Doctor’s qualifications and experience in this area of work:


[To set out details]







- 2 -


Doctor-patient relationship:

Please state if you have been seeing the patient regularly over a period of time (if so,
please state when you first started see ing the patient and how often you see the
patient) or if you saw the patient specifically for this mental capacity assessment only.


I have been the doctor in charge of Mr Tan Ah Kow since November 2010. I have
seen Mr Tan regularly since then, on average once or twice a year. For purposes of
this medical report, I re-examined Mr Tan on 20 June 2015.









SECTION 3: PATIENT’S MEDICAL INFORMATION


Patient’s clinical history:

Please also state the source of the information (e.g. from medical records,  from the
patient, from the applicant etc.).

Mr Tan Ah Kow was accompanied by his son, Mr Tan Ah Beng, for the examination.
Mr Tan is a 55 year old man, who is divorced, and unemployed. Mr Tan is currently
living with his son, Ah Beng, in Ah Beng’s flat. Mr Tan Ah Beng informed me that
Mr Tan Ah Kow used to work as a cleaner.

Mr Tan Ah Kow has a history of medical conditions. He has had hypertension and
hyperlipidemia since 1990 and suffered several strokes in 2005. He subsequently
developed heart problems (cardiomyopathy), cardiac failure and chronic renal disease
and was treated in ABC Hospital.

He was last admitted to the ABC Hospital on 1 April 2010 till 15 April 2010, during
which he was diagnosed to have suffered from a stroke. This was confirmed by CT
and MRI brain scans.

Thereafter, he was transferred to XYZ Hospital for stroke rehabilitation on 15 April
2010.

After that, Mr Tan was referred to Blackacre Hospital for follow-up treatment from in
November 2010. The clinical impression was that he was manifesting behavioural and
psychological symptoms secondary to Dementia.

- 3 -

The clinical impression was that he was manifesting behavioural and psychological
symptoms secondary to Dementia.

I was informed by Mr Tan Ah Beng that Mr Tan is at present incontinent, and is
unable to bathe or use the toilet on his own. He is, however, able to feed himself.

I have observed a gradual deterioration in his cognitive ability and physical state over
the years.



Findings from physical examination / mental state examination:

Please state your observations of the patient (i.e. the pa

In [42]:
if filename.lower().endswith(".pdf"):

    summary = summarize_medical_report(medical_report)

    print("=" * 80)
    print("AI GENERATED MEDICAL SUMMARY")
    print("=" * 80)

    print(summary)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=20) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
AI GENERATED MEDICAL SUMMARY
================================================================================
MEDICAL REPORT SECTION 1: PATIENT’S PARTICULARS Full name of patient: Tan Ah Moi NRIC/FIN/Passport no. of patient: S1111111X Age of patient: 55 years old SECTION 2: DOCTOR’s PARTICULARS Full name of doctor: Tan Ah Moi NRIC/FIN/Passport no. of doctor: 333333 Hospital / Clinic name and address: 1 Blackacre Hospital